services:
  mysql:
    image: 'mysql:latest'
    container_name: 'testdocker-mysql-1'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '34027:3306'
